---
image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

before_script:
  - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_TOKEN"

build:
  stage: build
  script:
    - docker build -t "$DOCKER_HUB_IMAGE:latest" -t "$DOCKER_HUB_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker push --all-tags "$DOCKER_HUB_IMAGE"
  only:
    - master
